### ISSUE TITLE
SSL Connector Issue

### ISSUE THREAD

**Issue by SubhamBurnwal** [agubelu/discord-bot-template#2]
I am not sure whether this is an issue my settings or not, but I get this exception:
File "E:\INSTALLED\Python\lib\ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1108)

which is the direct cause of the following exception:

File "E:\INSTALLED\Python\lib\site-packages\aiohttp\connector.py", line 938, in _wrap_create_connection
raise ClientConnectorCertificateError(
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host discord.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1108)')]

I could just turn ssl to False but that would be very unsafe. I have no idea how to proceed.

**Comment by agubelu** [comment]
The certificate for discord.com seems to be valid as of right now, so it may be due to an expired intermediate or root certificate on your end. See https://github.com/Rapptz/discord.py/issues/4159 for possible solutions.

**Comment by agubelu** [comment]
Closed due to inactivity
