### ISSUE TITLE
Execution of job "Some_Event.run" skipped: maximum number of running instances reached (1)

### ISSUE THREAD

**Issue by echan00** [agubelu/discord-bot-template#8]
I have an event that runs every minute. After 5-10 events I start receiving the following skipped events in my console:

`Execution of job "Some_Event.run (trigger: interval[0:01:00], next run at: 2020-12-17 10:26:09 PST)" skipped: maximum number of running instances reached (1)`

What could this be due to?  How would we get around this?

**Comment by agubelu** [comment]
Is there any chance that the event is taking more than 1 minute to run? I think APScheduler limits instances of the same event to 1 by default, which means that the event can't run if there's a previous instance of the same event still running.

If this is the case, you can get around it by adding a `max_instances=X` parameter when registering the event ([your_bot.py L50-51](https://github.com/agubelu/discord-bot-template/blob/master/your_bot.py#L50)), where X is the maximum amount of instances of the same event that can run at any given time.

**Comment by echan00** [comment]
Thanks @agubelu, let me look into this and see if I can find the issue.

**Comment by echan00** [comment]
Yes after thorough testing I can confirm increasing max_instances will resolve the issue. Thanks @agubelu
